config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :home do
  	get :get_user_list, on: :collection
  end
  resources :appointments
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :patient, class_name: "User"
    belongs_to :doctor, class_name: "User"

    validates :description, :booking_time, presence: true
    validate :validate_booking_time
    scope :doctor_appointments, ->(id) { where(doctor_id: id) }

    after_save    :add_appointment_number

    def add_appointment_number
    	appointment_number = Integer(self.appointment_number) rescue nil
    	update_column(:appointment_number, format('REG%.7d', id)) if self.appointment_number.blank?
    end

    def validate_booking_time
    	existing_time = booking_time.in_time_zone("Kolkata")
    	current_time = Time.now.in_time_zone("Kolkata") + 1.hours
    	if (existing_time < current_time)
    		errors.add(:booking_time, "Please book after #{current_time}")
    	end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  enum role: %i[doctor patient]

  scope :doctors, -> { where(role: 'doctor') }
  scope :patients, -> { where(role: 'patient') }

  # has_many :appointments
  has_many :patient_appointments, foreign_key: "patient_id", class_name: "Appointment"
  has_many :doctor_appointments, foreign_key: "doctor_id", class_name: "Appointment"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(users)
    home_index_path
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:studentid, :password, :remember_me) }
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  def index
  	@appointments = Appointment.doctor_appointments(params[:doctor_id])
  end

  def show
  	@appointment = Appointment.find(params[:id])
  end

  def new
  	@doctor_id = params[:doctor_id].present? ? params[:doctor_id] : ''
  	@appointment = Appointment.new
  end

  def create
  	@appointment = current_user.patient_appointments.new(appointment_params) 
  	params[:appointment][:booking_time] = params[:appointment][:booking_time].in_time_zone("Kolkata")
    if @appointment.save   
      flash[:notice] = 'Appointment added!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to edit appointment!'   
      render :new   
    end   
  end

  def edit
  	@appointment = Appointment.find(params[:id])
  end

  def update
  	@appointment = Appointment.find(params[:id])   
    if @appointment.update_attributes(appointment_params)   
      flash[:notice] = 'Appointment updated!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to edit appointment!'   
      render :edit   
    end   
  end

  def destroy
  	@appointment = Appointment.find(params[:id])
  	booking_time = @appointment.booking_time.in_time_zone("Kolkata") - 2.hours
  	cancel_time = Time.now.in_time_zone("Kolkata")
  	if booking_time > cancel_time
	  	if @appointment.delete   
	      flash[:notice] = 'Appointment deleted!'   
	    else   
	      flash[:error] = 'Failed to delete this appointment!'   
	    end  
	else
		flash[:error] = 'Appointment can not delete!'   
	end 
	redirect_to root_path   
  end

  private

  def appointment_params   
    params.require(:appointment).permit(:description, :booking_time, :appointment_number, :patient_id, :doctor_id)   
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:get_user_list]
  def index
	# @doctors = User.doctors.includes(:doctor_appointments)
	 @doctors = User.doctors.includes(:doctor_appointments)
	 @doctors = @doctors.select("users.*, (SELECT COUNT(appointments.id) FROM appointments where appointments.doctor_id = users.id) AS total_appointments")
  end

  def get_user_list
  	if params[:flag] == 'doctor'
  		render json: User.doctors 
  	elsif params[:flag] == 'patient'
  		render json: User.patients
  	else
  		render json: User.all
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

app/views/appointments/destroy.html.erb
<h1>Appointments#destroy</h1>
<p>Find me in app/views/appointments/destroy.html.erb</p>

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<div class="container">
	<% @appointments.each do |appointment| %>
		<div class="card" style="width: 18rem;">
		  <div class="card-body">
		    <h5 class="card-title"><%= appointment&.appointment_number %></h5>
		    <h6 class="card-subtitle mb-2 text-muted"><%= appointment&.booking_time %></h6>
		    <p class="card-text"><%= appointment&.description %></p>
		    <% if appointment.patient_id == current_user.id %>
		    	<%= link_to 'Cancel Appointment', appointment_path(appointment), :method => :delete %>
		    <% end %>
		  </div>
		</div>
	<% end %>
</div>

app/views/appointments/new.html.erb
<div class="container">   
  <%= form_for @appointment, url: {action: :create} do |f| %>   
      <div>   
        <h3>Add a Appointment</h3>   
      </div>   
      <div>   
        <p>   
          <%= "<div class='alert alert-primary' role='alert'>#{@appointment.errors.full_messages.first}</div>".html_safe if @appointment.errors.any? %>   
       <div class="form-group">
            <label class="control-label" for="datetimepicker-default">Select Booking Date and Time</label>  
              <%= f.text_field :booking_time, class: "form-control", id: "datetimepicker1" %>
        </div>   
        <div class="form-group">
           <label>Description</label>   
              <%= f.text_field :description, class: "form-control" %>   
        </div>   
        <div>   
             <%= f.hidden_field :doctor_id, value: @doctor_id %>   
        </div>   
         </p>   
      </div>   
      <div>   
        <%= link_to 'Back', { controller: 'home', action: 'index'} %>   
        <%= f.submit 'Create Appointment' %>   
      </div>   
  <% end %>   
</div> 
<script type="text/javascript">
  const el = document.getElementById('datetimepicker1');
  var newDate = new Date(new Date().setHours(new Date().getHours() + 1));
  flatpickr(el, {
    enableTime:      true,
    altInput:        true,
    defaultDate:     newDate,
    minDate:         "today",
    defaultHour:     23,
    defaultMinute:   59,
    minuteIncrement: 1,
    time_24hr: true,
    onOpen: [
        function(selectedDates, dateStr, instance){
          
        }
    ],
    onClose: function(selectedDates, dateStr, instance){
      expiryDate = new Date(new Date().setHours(new Date().getHours() + 1));
        if (expiryDate > new Date(dateStr)){
          alert("Please book after "+newDate)
        }
    }
  });
</script>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/appointments/update.html.erb
<h1>Appointments#update</h1>
<p>Find me in app/views/appointments/update.html.erb</p>

app/views/home/index.html.erb
<% if current_user.role == 'patient'%>
<div class="container">
    <h1>Doctors List</h1>
	<table class="table table-striped">
	  <thead class="thead-dark">
	    <tr>
	      <th scope="col">Name</th>
	      <th scope="col">Total Appointment</th>
	      <th scope="col"></th>
	    </tr>
	  </thead>
	    <tbody>
		  	<% @doctors.each do |doctor| %>
			    <!-- <li><%#= "#{doctor.name}" %> <%#= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></li> -->
			    <tr>
			      <td><%= link_to "#{doctor.name}", new_appointment_path(doctor_id: doctor.id) %></td>
			      <td><%= link_to "#{doctor&.total_appointments}", appointments_path(doctor_id: doctor.id) %></td>
			      <td></td>
			    </tr>
			<% end %>
	    </tbody>
	</table>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticalTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if user_signed_in? %>
		<div class="container"> 
			<div>Hello <%= "#{current_user&.name}" %>
				<p><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></p>
			</div>
		</div>
	<% end %>
	<%= yield %>
  </body>
</html>